name: tlm
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^25.1.41
  syncfusion_flutter_pdf: ^25.1.39
  file_picker: ^8.0.0+1
  dotted_border: ^2.1.0
  iconsax: ^0.0.8
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  provider: ^6.1.2
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  connectivity_plus: ^6.0.3
  background_downloader: ^8.4.3
  shimmer: ^3.0.0
  window_manager: ^0.3.8
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe-Regular.ttf
    - family: SegoeSemiBold
      fonts:
        - asset: assets/fonts/Segoe-SemiBold.ttf
    - family: SegoeBold
      fonts:
        - asset: assets/fonts/Segoe-Bold.ttf
    - family: SegoeLight
      fonts:
        - asset: assets/fonts/Segoe-Light.ttf
    - family: SegoeItalic
      fonts:
        - asset: assets/fonts/Segoe-Italic.ttf